from room import Room, Direction, Portal


rooms = [Room('A1',
              'You wake up in small room with a headache.  You you realize that you must have been kidnapped and brought here by evil forces. You need to find your way out of the dungeon as quickly as possible!  What would you like to do?',
              [Portal(Direction.EAST, 'A2'),
               Portal(Direction.SOUTH, 'B1')],
              []),
         Room('A2',
              'A small barred skylight in the celing provides dim light for the room and the hint of freedom that may await you.',
              [Portal(Direction.EAST, 'A3'),
               Portal(Direction.WEST, 'A1')],
              []),
         Room('A3',
              'You are suprised by rats running from the room as you enter.',
              [Portal(Direction.EAST, 'A4'),
               Portal(Direction.WEST, 'A2')],
              []),
         Room('A4',
              'A small stream of water flows along the edge of the room.',
              [Portal(Direction.SOUTH, 'B4'),
               Portal(Direction.WEST, 'A3')],
              []),
         Room('A7',
              'A Magic Mouth on North wall says "I bet you will be stuck in here as long as I have been!"',
              [Portal(Direction.EAST, 'A8')],
              []),
         Room('A8',
              'This room is completely empty.',
              [Portal(Direction.EAST, 'A9'),
               Portal(Direction.WEST, 'A7')],
              []),
         Room('A9',
              'There is a black fog floating in the air.',
              [Portal(Direction.EAST, 'A10'),
               Portal(Direction.SOUTH, 'B9'),
               Portal(Direction.WEST, 'A8')],
              []),
         Room('A10',
              'There is a large pit in the ground.  It might be possible to climb down into it.',
              [Portal(Direction.EAST, 'A11'),
               Portal(Direction.WEST, 'A9'),
               Portal(Direction.SOUTH, 'B10'),
               Portal(Direction.DOWN, 'PIT_A10')],
              []),
         Room('A11',
              'You wonder if you will ever find your way out of this place.',
              [Portal(Direction.WEST, 'A10'),
               Portal(Direction.SOUTH, 'B11')],
              []),

         Room('B1',
              'Something smells terrible in here.  You see a pair of red glowing in the shadows.  You better leave quickly.',
              [Portal(Direction.NORTH, 'A1'),
               Portal(Direction.EAST, 'B2')],
              []),
         Room('B2',
              'There\'s a large table  full of food.  When you try to eat some, it disappears.  It must have been an illusion.  This place is evil!',
              [Portal(Direction.WEST, 'B1'),
               Portal(Direction.SOUTH, 'C2')],
              []),
         Room('B3',
              'Dead End.',
              [Portal(Direction.SOUTH, 'C3')],
              []),
         Room('B4',
              'A chill crawls up your spine and out over your skin as you look upon this room. The carvings on the wall are terrifying.',
              [Portal(Direction.NORTH, 'A4'),
               Portal(Direction.EAST, 'B5')],
              []),
         Room('B5',
              'A dark green and white moss covers the whole room.',
              [Portal(Direction.WEST, 'B4'),
               Portal(Direction.EAST, 'B6')],
              []),
         Room('B6',
              'There is a skeleton holding a ripped note that reads "To exit this place you keep a good pace. The south - east corner of the dungeon is the answer."',
              [Portal(Direction.WEST, 'B5'),
               Portal(Direction.SOUTH, 'C6')],
              []),
         Room('B9',
              'It looks like there is a trap of some sort in the middle of the room. You should avoid it',
              [Portal(Direction.NORTH, 'A9'),
               Portal(Direction.SOUTH, 'C9')],
              []),
         Room('B10',
              'A frog hops out from the shadows.  You hear "Croooak" before it disappears with a loud pop.',
              [Portal(Direction.NORTH, 'A10'),
               Portal(Direction.EAST, 'B11'),
               Portal(Direction.SOUTH, 'C10')],
              []),
         Room('B11',
              'The room is completely dark.  You can\'t see any exits.',
              [Portal(Direction.WEST, 'B10'),
               Portal(Direction.SOUTH, 'C11'),
               Portal(Direction.NORTH, 'A11')],
              []),

         Room('C1',
              'There are bones scattered around the chamber.',
              [Portal(Direction.SOUTH, 'D1')],
              []),
         Room('C2',
              'When you open the door, you feel a strange magical prescence.  The door to the south is faintly glowing purple.  You wonder where it goes?',
              [Portal(Direction.SOUTH, 'A1')],
              []),
         Room('C3',
              'You can barely make out quite whispers coming from the distance but it\'s difficult to determine the direction.',
              [Portal(Direction.NORTH, 'B3'),
               Portal(Direction.EAST, 'C4')],
              []),
         Room('C4',
              'On the north wall you see a message scratched into the stone. It reads, "The end is near."',
              [Portal(Direction.WEST, 'C3'),
               Portal(Direction.SOUTH, 'D4'),
               Portal(Direction.EAST, 'C5')],
              []),
         Room('C5',
              'The room is filled with smoke from a recent fire.  Someone must have camped here recently.',
              [Portal(Direction.WEST, 'C4')],
              []),
         Room('C6',
              'You hear footsteps outside the North door.',
              [Portal(Direction.NORTH, 'B6'),
               Portal(Direction.SOUTH, 'D6')],
              []),
         Room('C9',
              'A completely empty room.  Why?',
              [Portal(Direction.NORTH, 'B10'),
               Portal(Direction.SOUTH, 'D9')],
              []),
         Room('C10',
              'The room is oddly tilted to the west making for difficult travel.',
              [Portal(Direction.EAST, 'C11'),
               Portal(Direction.NORTH, 'B10'),
               Portal(Direction.SOUTH, 'D10')],
              []),
         Room('C11',
              'You trip on a loose stone and stumble against the wall.',
              [Portal(Direction.WEST, 'C10'),
               Portal(Direction.NORTH, 'B11'),
               Portal(Direction.SOUTH, 'D11')],
              []),

         Room('D1',
              'The room is filled with over 600 butterflies, you can barely see the exits.',
              [Portal(Direction.NORTH, 'C1'),
               Portal(Direction.EAST, 'D2'),
               Portal(Direction.SOUTH, 'E1')],
              []),
         Room('D2',
              'The room is filled with larger with large boulders making it hard to move in.',
              [Portal(Direction.WEST, 'D1')],
              []),
         Room('D3',
              'The room was clearly a jail cell. There is long forgotten skelton behind the bars.  You are happy its not you.',
              [Portal(Direction.EAST, 'D4')],
              []),
         Room('D4',
              'This room is full of spider webs.  You sense movement out of the corner of your eye.  Better not stick around too long.',
              [Portal(Direction.NORTH, 'C4'),
               Portal(Direction.WEST, 'D3')],
              []),
         Room('D5',
              'There\'s a broken bucket on the floor',
              [Portal(Direction.EAST, 'D6'),
               Portal(Direction.SOUTH, 'E5')],
              []),
         Room('D6',
              'There\'s a small grate in the floor.',
              [Portal(Direction.NORTH, 'C6'),
               Portal(Direction.EAST, 'D7'),
               Portal(Direction.WEST, 'D5')],
              []),
         Room('D7',
              'There\'s rope hanging down from a grate in the ceiling.  You might be able to reach it.',
              [Portal(Direction.EAST, 'D8'),
               Portal(Direction.WEST, 'D6'),
               Portal(Direction.UP, 'UP_D7')],
              []),
         Room('D8',
              'The is a bright light coming from the ceiling.  You can\'t see anything.',
              [Portal(Direction.EAST, 'D9'),
               Portal(Direction.WEST, 'D7')],
              []),
         Room('D9',
              'Another empty room!  The maze is madenning!',
              [Portal(Direction.NORTH, 'C9'),
               Portal(Direction.WEST, 'D8')],
              []),
         Room('D10',
              'I\'m getting hungry.  You wonder if this will ever end?',
              [Portal(Direction.SOUTH, 'E10'),
               Portal(Direction.WEST, 'D9'),
               Portal(Direction.NORTH, 'C10')],
              []),
         Room('D11',
              'There is a skelton chained to the wall.  His finger is oddly pointing south.',
              [Portal(Direction.NORTH, 'C11'),
               Portal(Direction.WEST, 'D10'),
               Portal(Direction.SOUTH, 'E11')],
              []),
         Room('E1',
              'The exit feels like it\s a long ways away.',
              [Portal(Direction.NORTH, 'D1'),
               Portal(Direction.SOUTH, 'F1')],
              []),
         Room('E5',
              'The floor of this room is covered with dead instects of every type.  You can\'t understand why.',
              [Portal(Direction.NORTH, 'D5')],
              []),
         Room('E9',
              'You see ladder that goes up and smell the scent of fresh air.  You wonder could this be the exit?',
              [Portal(Direction.EAST, 'E10'),
               Portal(Direction.UP, 'EXIT')],
              []),
         Room('E10',
              'The floor is cover with sticky goo. It\'s nearly impossible to walk here.',
              [Portal(Direction.NORTH, 'D10'),
               Portal(Direction.WEST, 'E9')],
              []),
         Room('E11',
              'A gust of wind blows you backwards as you open the door but you are able to fight your way into the room.',
              [Portal(Direction.NORTH, 'D11'),
               Portal(Direction.WEST, 'E10')],
              []),
         Room('F1',
              'Oh no, it\'s a dead end.',
              [Portal(Direction.NORTH, 'E1')],
              []),
         Room('PIT_A10',
              'With some difficulty, you manage to climb down.',
              [Portal(Direction.UP, 'A10')],
              []),
         Room('UP_D7',
              'You are barely able to climb the rope to grate but you mange to slip through. The rooms is unfortunately empty.',
              [Portal(Direction.DOWN, 'D7')],
              []),
         Room('EXIT',
              'You made it Out Alive!!! Good job on finding your way out.  Time for dinner. Thanks for playing.',
              [],
              []),
         ]

# rooms = [Room('A1',
#               'You are in a small room, you see exits to the east and south and sword laying on the ground.',
#               [Portal(Direction.EAST, 'A2'),
#                Portal(Direction.SOUTH, 'B1')],
#               []),
#
#          Room('A2', 'This is a small room,  you see an exit to the south and west.',
#          [Portal(Direction.WEST, 'A1'),
#           Portal(Direction.SOUTH, 'B2')],
#          []),
#
#          Room('A3', 'This is a small room,  you see an exit to the south.',
#          [Portal(Direction.SOUTH, 'B3')],
#          []),
#
#          Room('B1', 'This is a small room,  you see exits to the north and east.',
#          [Portal(Direction.NORTH, 'A1'),
#           Portal(Direction.EAST, 'B2')],
#          []),
#
#          Room('B2', 'This is a small room,  you see an exit to the west, north and east.',
#          [Portal(Direction.WEST, 'B1'),
#           Portal(Direction.NORTH, 'A2'),
#           Portal(Direction.EAST, 'B3')],
#          []),
#
#          Room('B3', 'This is a small room,  you see an exit to the north, south and west.',
#          [Portal(Direction.WEST, 'B2'),
#           Portal(Direction.NORTH, 'B1'),
#           Portal(Direction.SOUTH, 'C3')],
#          []),
#
#          Room('C1', 'You must close to the end, there is a ladder up and an exit to the east.',
#          [Portal(Direction.EAST, 'C2'), Portal(Direction.UP, 'DONE')],
#          []),
#
#          Room('C2', 'This is a small room,  you see an exit to the west and east.',
#          [Portal(Direction.WEST, 'C1'),
#           Portal(Direction.EAST, 'C3')],
#          []),
#
#          Room('C3', 'This is a small room,  you see an exit to the west and north.',
#          [Portal(Direction.WEST, 'C2'),
#           Portal(Direction.NORTH, 'B3')],
#          []),
#
#          Room('DONE', 'You are in a room full of gold. You win!!!!',
#          [],
#          []),
#
#          ]


def room_from_id(id):
    for m_room in rooms:
        if id == m_room.id:
            return m_room
    return None
